-- Generated by scripts/generate-news-items-seed.ts (offline, from fixtures)
-- Demo seed for public.news_items so the /news page has deterministic data before the live collector runs.
-- The live news-collector daemon upserts real items on the same conflict key (external_id).
-- Rows: 8

insert into public.news_items (
  external_id,
  source_key,
  source_name,
  source_kind,
  title,
  url,
  summary,
  ecosystem_layer,
  ecosystem_layer_label,
  tags,
  lang,
  published_at,
  published_date,
  collected_at,
  collected_date,
  enriched,
  metadata
)
values
  ('d675c4e837e30989c0648a6af91fd10e', 'fx-qbitai', '量子位', 'cn-media', 'Anthropic 发布 Claude 新模型，上下文窗口大幅扩展', 'https://www.qbitai.com/2026/06/anthropic-claude.html', 'Anthropic 正式发布新一代 Claude 模型，主打更长上下文与更稳的工具调用。', 'model-platform', '模型与托管平台', array['Anthropic', '模型与托管平台']::text[], 'zh', '2026-06-16T13:23:06.000Z', '2026-06-16', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":"https://www.qbitai.com/2026/06/anthropic-claude.html","categories":[],"sourceUrl":"https://www.qbitai.com/feed"}'::jsonb),
  ('5545a0dfbd4df9c6a97b6479b4ed6189', 'fx-qbitai', '量子位', 'cn-media', 'MCP 协议迎来重大更新，跨厂商互操作性增强', 'https://www.qbitai.com/2026/06/mcp-update.html', 'Model Context Protocol 发布新版本，强化授权与多客户端互操作。', 'protocol', '协议与互操作', array['MCP', '协议与互操作']::text[], 'zh', '2026-06-16T10:36:35.000Z', '2026-06-16', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":"https://www.qbitai.com/2026/06/mcp-update.html","categories":[],"sourceUrl":"https://www.qbitai.com/feed"}'::jsonb),
  ('018c59b070704b224b724d4dea419137', 'fx-qbitai', '量子位', 'cn-media', 'RAG 检索增强与向量记忆实战解析', 'https://www.qbitai.com/2026/06/rag-memory.html', '从 retrieval 到向量 memory，系统拆解 RAG 检索增强链路。', 'data-memory', '数据与记忆', array['RAG', '数据与记忆']::text[], 'zh', '2026-06-15T09:10:00.000Z', '2026-06-15', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":"https://www.qbitai.com/2026/06/rag-memory.html","categories":[],"sourceUrl":"https://www.qbitai.com/feed"}'::jsonb),
  ('9d4f59b8ad415a5fa20ab7fbc0dd74b0', 'fx-decoder', 'The Decoder', 'en-media', 'LangGraph adds multi-agent orchestration runtime for production', 'https://the-decoder.com/langgraph-multi-agent-orchestration/', 'LangGraph ships a production-grade runtime for multi-agent orchestration and workflows.', 'runtime', '编排 Runtime', array['LangChain', '编排 Runtime']::text[], 'en', '2026-06-16T19:32:38.000Z', '2026-06-16', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":"https://the-decoder.com/langgraph-multi-agent-orchestration/","categories":[],"sourceUrl":"https://the-decoder.com/feed/"}'::jsonb),
  ('d4f0733a329ca8a8549b599bc0781954', 'fx-decoder', 'The Decoder', 'en-media', 'New SWE-bench benchmark evaluates coding agents at scale', 'https://the-decoder.com/swe-bench-benchmark-agents/', 'A refreshed SWE-bench leaderboard evaluates how coding agents perform across repositories.', 'evaluation', '评测与基准', array['Benchmark', '评测与基准']::text[], 'en', '2026-06-16T18:19:40.000Z', '2026-06-16', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":"https://the-decoder.com/swe-bench-benchmark-agents/","categories":[],"sourceUrl":"https://the-decoder.com/feed/"}'::jsonb),
  ('47c8f0ae1a79a7b6d5e08088a1be1196', 'fx-decoder', 'The Decoder', 'en-media', 'Prompt injection attack bypasses guardrails, OWASP issues warning', 'https://the-decoder.com/prompt-injection-guardrails-owasp/', 'Researchers show a prompt injection that bypasses agent guardrails; OWASP updates its security guidance.', 'security-governance', '安全与治理', array['安全与治理']::text[], 'en', '2026-06-16T15:16:08.000Z', '2026-06-16', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":"https://the-decoder.com/prompt-injection-guardrails-owasp/","categories":[],"sourceUrl":"https://the-decoder.com/feed/"}'::jsonb),
  ('9bde0244def9de48eb19b409d24068dc', 'fx-atom', 'Vendor Engineering Blog', 'vendor-blog', 'Cursor ships an agentic copilot for developers', 'https://example.com/blog/cursor-agentic-copilot', 'Cursor brings an agentic copilot experience to its developer IDE.', 'product-ui', '产品与交互', array['Microsoft', '产品与交互']::text[], 'en', '2026-06-16T09:00:00.000Z', '2026-06-16', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":null,"categories":[],"sourceUrl":"https://example.com/feed"}'::jsonb),
  ('5d7ee64e13a1135508e2915c98404960', 'fx-atom', 'Vendor Engineering Blog', 'vendor-blog', 'A survey overview of autonomous agents', 'https://example.com/blog/autonomous-agents-survey', 'A broad overview that maps the landscape of autonomous agents for newcomers.', 'foundation', '基础综述', array['基础综述']::text[], 'en', '2026-06-15T08:00:00.000Z', '2026-06-15', '2026-06-17T00:00:00.000Z', '2026-06-17', false, '{"guid":null,"categories":[],"sourceUrl":"https://example.com/feed"}'::jsonb)
on conflict (external_id) do update set
  source_key = excluded.source_key,
  source_name = excluded.source_name,
  source_kind = excluded.source_kind,
  title = excluded.title,
  url = excluded.url,
  summary = excluded.summary,
  ecosystem_layer = excluded.ecosystem_layer,
  ecosystem_layer_label = excluded.ecosystem_layer_label,
  tags = excluded.tags,
  lang = excluded.lang,
  published_at = excluded.published_at,
  published_date = excluded.published_date,
  collected_at = excluded.collected_at,
  collected_date = excluded.collected_date,
  enriched = excluded.enriched,
  metadata = excluded.metadata,
  updated_at = now();
