-- Generated by scripts/generate-notion-articles-seed.ts (offline, from sample-data)
-- Demo seed for public.notion_articles so the /notion page has deterministic data before the live sync runs.
-- The live notion-sync upserts real articles on the same conflict key (notion_page_id).
-- Rows: 2

insert into public.notion_articles (
  notion_page_id,
  slug,
  source_key,
  title,
  summary,
  body_markdown,
  cover_image_url,
  tags,
  status,
  published_at,
  published_date,
  notion_url,
  notion_last_edited_time,
  metadata
)
values
  ('be633bf1-dfa0-436d-b259-571129a590e5', 'notion-sync-architecture', 'sample', '把 Notion 文章接入站点：一次同步管线设计', '新建 notion_articles 表，blocks→markdown 全文同步，图片重托管，cron+CLI 共用一个 syncNotion 入口。', '# 把 Notion 文章接入站点

本文演示 Notion 全文同步的整体架构：

## 数据流

- Notion 数据库（已发布页）
- `databases.query` 增量拉取（`last_edited_time` 高水位）
- `notion-to-md` 把 blocks 转成 markdown
- 图片从临时 S3 URL 重托管到稳定存储
- 幂等 upsert 到 `notion_articles`（冲突键 `notion_page_id`）

## 渲染

列表页与详情页运行时 anon 只读，详情正文经 `markdown-it` + DOMPurify 渲染。

```ts
const report = await syncFromConfig(loadNotionConfig());
```', null, array['notion', 'architecture', 'supabase']::text[], 'published', '2026-06-17T00:00:00.000Z', '2026-06-17', 'https://www.notion.so/sample-notion-sync-architecture', '2026-06-17T08:30:00.000Z', '{"sample":true}'::jsonb),
  ('aa11bb22-cc33-dd44-ee55-ff6677889900', 'incremental-sync-and-idempotency', 'sample', '增量同步与幂等：为什么用 last_edited_time 做高水位', '无状态高水位 + on_conflict 幂等 upsert，让重复运行不增行、崩溃可安全续跑。', '# 增量同步与幂等

高水位取库内 `max(notion_last_edited_time)`，无需 state 文件。

1. 升序排 `last_edited_time`，水位单调推进
2. `on_or_after` 含界，边界页会被重取
3. 幂等 upsert 让重取成为 no-op

> 这样即便同步中途崩溃，下次也能从上次水位安全续跑。', null, array['notion', 'incremental', 'idempotency']::text[], 'published', '2026-06-16T00:00:00.000Z', '2026-06-16', 'https://www.notion.so/sample-incremental-sync', '2026-06-16T09:00:00.000Z', '{"sample":true}'::jsonb)
on conflict (notion_page_id) do update set
  slug = excluded.slug,
  source_key = excluded.source_key,
  title = excluded.title,
  summary = excluded.summary,
  body_markdown = excluded.body_markdown,
  cover_image_url = excluded.cover_image_url,
  tags = excluded.tags,
  status = excluded.status,
  published_at = excluded.published_at,
  published_date = excluded.published_date,
  notion_url = excluded.notion_url,
  notion_last_edited_time = excluded.notion_last_edited_time,
  metadata = excluded.metadata,
  updated_at = now();
