// 离线样例文章：供 seed 生成与 push 脚本使用，让 /notion 页在首次真实同步前有确定性数据可渲染。
// 不含真实密钥/网络；body_markdown 为课程自撰示例正文。

import type { NotionArticle } from "./types.ts";

export const SAMPLE_NOTION_ARTICLES: readonly NotionArticle[] = [
  {
    notionPageId: "be633bf1-dfa0-436d-b259-571129a590e5",
    slug: "notion-sync-architecture",
    sourceKey: "sample",
    title: "把 Notion 文章接入站点：一次同步管线设计",
    summary: "新建 notion_articles 表，blocks→markdown 全文同步，图片重托管，cron+CLI 共用一个 syncNotion 入口。",
    bodyMarkdown: [
      "# 把 Notion 文章接入站点",
      "",
      "本文演示 Notion 全文同步的整体架构：",
      "",
      "## 数据流",
      "",
      "- Notion 数据库（已发布页）",
      "- `databases.query` 增量拉取（`last_edited_time` 高水位）",
      "- `notion-to-md` 把 blocks 转成 markdown",
      "- 图片从临时 S3 URL 重托管到稳定存储",
      "- 幂等 upsert 到 `notion_articles`（冲突键 `notion_page_id`）",
      "",
      "## 渲染",
      "",
      "列表页与详情页运行时 anon 只读，详情正文经 `markdown-it` + DOMPurify 渲染。",
      "",
      "```ts",
      "const report = await syncFromConfig(loadNotionConfig());",
      "```",
    ].join("\n"),
    coverImageUrl: null,
    tags: ["notion", "architecture", "supabase"],
    status: "published",
    publishedAt: "2026-06-17T00:00:00.000Z",
    publishedDate: "2026-06-17",
    notionUrl: "https://www.notion.so/sample-notion-sync-architecture",
    notionLastEditedTime: "2026-06-17T08:30:00.000Z",
    metadata: { sample: true },
  },
  {
    notionPageId: "aa11bb22-cc33-dd44-ee55-ff6677889900",
    slug: "incremental-sync-and-idempotency",
    sourceKey: "sample",
    title: "增量同步与幂等：为什么用 last_edited_time 做高水位",
    summary: "无状态高水位 + on_conflict 幂等 upsert，让重复运行不增行、崩溃可安全续跑。",
    bodyMarkdown: [
      "# 增量同步与幂等",
      "",
      "高水位取库内 `max(notion_last_edited_time)`，无需 state 文件。",
      "",
      "1. 升序排 `last_edited_time`，水位单调推进",
      "2. `on_or_after` 含界，边界页会被重取",
      "3. 幂等 upsert 让重取成为 no-op",
      "",
      "> 这样即便同步中途崩溃，下次也能从上次水位安全续跑。",
    ].join("\n"),
    coverImageUrl: null,
    tags: ["notion", "incremental", "idempotency"],
    status: "published",
    publishedAt: "2026-06-16T00:00:00.000Z",
    publishedDate: "2026-06-16",
    notionUrl: "https://www.notion.so/sample-incremental-sync",
    notionLastEditedTime: "2026-06-16T09:00:00.000Z",
    metadata: { sample: true },
  },
];
