// 新闻源注册表。
//
// 启用源只保留公开 RSS/Atom feed；HTML 适配器只留作离线测试/后续候选，不直接订阅。
// 2026-06-25 live probe 只保留可解析且能返回条目的订阅源。
// 启用源必须经现有 fetchFeed live probe 可解析且能返回条目；已知临时不可用源可保留注册但设为 disabled。
// 单源失败只 skip+log，不影响其它源——这是真实聚合器的核心健壮性。

import type { NewsSource } from "./types.ts";

export const SOURCES: readonly NewsSource[] = [
  // —— 实测稳定 ——
  {
    key: "qbitai",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    kind: "cn-media",
    lang: "zh",
    enabled: true,
  },
  {
    key: "aibase-news",
    name: "AIBase 新闻",
    url: "https://news.aibase.com/zh/news",
    kind: "cn-media",
    lang: "zh",
    format: "aibase-html",
    layerHint: "model-platform",
    enabled: true,
  },

  {
    key: "techweb-it",
    name: "TechWeb 业界",
    url: "https://www.techweb.com.cn/rss/it.xml",
    kind: "cn-media",
    lang: "zh",
    enabled: true,
  },
  {
    key: "36kr-feed",
    name: "36Kr",
    url: "https://36kr.com/feed",
    kind: "cn-media",
    lang: "zh",
    layerHint: "product-ui",
    enabled: true,
  },
  {
    key: "ithome",
    name: "IT之家",
    url: "https://www.ithome.com/rss/",
    kind: "cn-media",
    lang: "zh",
    layerHint: "product-ui",
    enabled: true,
  },
  {
    key: "sspai",
    name: "少数派",
    url: "https://sspai.com/feed",
    kind: "cn-media",
    lang: "zh",
    layerHint: "product-ui",
    enabled: true,
  },
  {
    key: "the-decoder",
    name: "The Decoder",
    url: "https://the-decoder.com/feed/",
    kind: "en-media",
    lang: "en",
    critical: true,
    enabled: true,
  },
  {
    key: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    url: "http://export.arxiv.org/rss/cs.AI",
    kind: "paper",
    lang: "en",
    critical: true,
    enabled: true,
  },
  {
    key: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    url: "https://rss.arxiv.org/rss/cs.LG",
    kind: "paper",
    lang: "en",
    layerHint: "foundation",
    critical: true,
    enabled: true,
  },
  {
    key: "hn-ai",
    name: "Hacker News · AI",
    url: "https://hnrss.org/newest?q=AI+OR+LLM+OR+agent&count=30",
    kind: "community",
    lang: "en",
    enabled: true,
  },
  {
    key: "hn-frontpage",
    name: "Hacker News Front Page",
    url: "https://hnrss.org/frontpage",
    kind: "community",
    lang: "en",
    enabled: true,
  },
  {
    key: "linuxdo-latest",
    name: "LinuxDo 最新",
    url: "https://linux.do/latest.rss",
    kind: "community",
    lang: "zh",
    layerHint: "runtime",
    // 2026-07-06: Cloudflare returns cf-mitigated: challenge / HTTP 403 to Node fetch.
    enabled: false,
  },
  {
    key: "github-engineering",
    name: "GitHub Engineering Blog",
    url: "https://github.blog/engineering/feed/",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "github-changelog",
    name: "GitHub Changelog",
    url: "https://github.blog/changelog/feed/",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "google-ai",
    name: "Google AI Blog",
    url: "https://blog.google/innovation-and-ai/technology/ai/rss/",
    fallbackUrls: ["https://blog.google/technology/ai/rss/"],
    kind: "vendor-blog",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "deepmind",
    name: "Google DeepMind Blog",
    url: "https://deepmind.google/blog/rss.xml",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "microsoft-ai-source",
    name: "Microsoft Source · AI",
    url: "https://news.microsoft.com/source/topics/ai/feed/",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    enabled: true,
  },
  {
    key: "aws-ml",
    name: "AWS Machine Learning Blog",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    enabled: true,
  },
  {
    key: "nvidia-deep-learning",
    name: "NVIDIA Deep Learning",
    url: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    enabled: true,
  },
  {
    key: "infoq-ai",
    name: "InfoQ AI/ML/Data Engineering",
    url: "https://feed.infoq.com/ai-ml-data-eng",
    kind: "en-media",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    enabled: true,
  },
  {
    key: "venturebeat-ai",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    kind: "en-media",
    lang: "en",
    layerHint: "product-ui",
    enabled: true,
  },
  {
    key: "mit-tr",
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    kind: "en-media",
    lang: "en",
    enabled: true,
  },
  {
    key: "ahead-of-ai",
    name: "Ahead of AI",
    url: "https://magazine.sebastianraschka.com/feed",
    kind: "en-media",
    lang: "en",
    layerHint: "foundation",
    critical: true,
    enabled: true,
  },
  // —— 官方框架 / SDK release feed：补足 Agent 工程实践层 —— 
  {
    key: "openai-agents-python-releases",
    name: "OpenAI Agents Python Releases",
    url: "https://github.com/openai/openai-agents-python/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "openai-agents-js-releases",
    name: "OpenAI Agents JS Releases",
    url: "https://github.com/openai/openai-agents-js/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "langgraph-releases",
    name: "LangGraph Releases",
    url: "https://github.com/langchain-ai/langgraph/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "crewai-releases",
    name: "CrewAI Releases",
    url: "https://github.com/crewAIInc/crewAI/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "google-adk-releases",
    name: "Google ADK Releases",
    url: "https://github.com/google/adk-python/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "google-python-genai-releases",
    name: "Google Gen AI SDK Releases",
    url: "https://github.com/googleapis/python-genai/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "microsoft-autogen-releases",
    name: "Microsoft AutoGen Releases",
    url: "https://github.com/microsoft/autogen/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "semantic-kernel-releases",
    name: "Semantic Kernel Releases",
    url: "https://github.com/microsoft/semantic-kernel/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "openai-python-releases",
    name: "OpenAI Python SDK Releases",
    url: "https://github.com/openai/openai-python/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "letta-releases",
    name: "Letta Releases",
    url: "https://github.com/letta-ai/letta/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "data-memory",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "smolagents-releases",
    name: "smolagents Releases",
    url: "https://github.com/huggingface/smolagents/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  // —— 2026-07-06 supplemental live-probed agent / SDK / observability release feeds ——
  {
    key: "vercel-ai-releases",
    name: "Vercel AI SDK Releases",
    url: "https://github.com/vercel/ai/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "mcp-typescript-sdk-releases",
    name: "MCP TypeScript SDK Releases",
    url: "https://github.com/modelcontextprotocol/typescript-sdk/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "protocol",
    enabled: true,
  },
  {
    key: "mcp-python-sdk-releases",
    name: "MCP Python SDK Releases",
    url: "https://github.com/modelcontextprotocol/python-sdk/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "protocol",
    enabled: true,
  },
  {
    key: "mastra-releases",
    name: "Mastra Releases",
    url: "https://github.com/mastra-ai/mastra/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "pydantic-ai-releases",
    name: "Pydantic AI Releases",
    url: "https://github.com/pydantic/pydantic-ai/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "browser-use-releases",
    name: "browser-use Releases",
    url: "https://github.com/browser-use/browser-use/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "stagehand-releases",
    name: "Stagehand Releases",
    url: "https://github.com/browserbase/stagehand/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "product-ui",
    enabled: true,
  },
  {
    key: "openhands-releases",
    name: "OpenHands Releases",
    url: "https://github.com/All-Hands-AI/OpenHands/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "swe-agent-releases",
    name: "SWE-agent Releases",
    url: "https://github.com/SWE-agent/SWE-agent/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "evaluation",
    enabled: true,
  },
  {
    key: "aider-releases",
    name: "Aider Releases",
    url: "https://github.com/Aider-AI/aider/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "runtime",
    enabled: true,
  },
  {
    key: "mem0-releases",
    name: "Mem0 Releases",
    url: "https://github.com/mem0ai/mem0/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "data-memory",
    enabled: true,
  },
  {
    key: "graphiti-releases",
    name: "Graphiti Releases",
    url: "https://github.com/getzep/graphiti/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "data-memory",
    enabled: true,
  },
  {
    key: "humanlayer-releases",
    name: "HumanLayer Releases",
    url: "https://github.com/humanlayer/humanlayer/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "security-governance",
    enabled: true,
  },
  {
    key: "langfuse-releases",
    name: "Langfuse Releases",
    url: "https://github.com/langfuse/langfuse/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "evaluation",
    enabled: true,
  },
  {
    key: "phoenix-releases",
    name: "Arize Phoenix Releases",
    url: "https://github.com/Arize-ai/phoenix/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "evaluation",
    enabled: true,
  },
  {
    key: "llamaindex-python-releases",
    name: "LlamaIndex Python Releases",
    url: "https://github.com/run-llama/llama_index/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "data-memory",
    enabled: true,
  },
  {
    key: "dspy-releases",
    name: "DSPy Releases",
    url: "https://github.com/stanfordnlp/dspy/releases.atom",
    kind: "release",
    lang: "en",
    layerHint: "evaluation",
    enabled: true,
  },
  // —— live probe verified feeds ——
  {
    key: "huggingface",
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    kind: "vendor-blog",
    lang: "en",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
  {
    key: "openai",
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    kind: "vendor-blog",
    lang: "en",
    layerHint: "model-platform",
    critical: true,
    retry: { maxAttempts: 5, baseDelayMs: 1_000 },
    enabled: true,
  },
];

/** 仅取启用的源；cron/collect 都走这个入口。 */
export function enabledSources(): readonly NewsSource[] {
  return SOURCES.filter((source) => source.enabled);
}

export function findSource(key: string): NewsSource | undefined {
  return SOURCES.find((source) => source.key === key);
}

