-- Persist source-preserving Simplified Chinese translations for RSS articles.
-- Translation is generated by news-collector; the browser only switches cached text.

alter table public.news_items
  add column if not exists title_zh text not null default '',
  add column if not exists summary_zh text not null default '',
  add column if not exists content_text_zh text not null default '',
  add column if not exists translation_status text not null default 'not_requested' check (
    translation_status in ('not_requested', 'translated', 'skipped', 'failed')
  ),
  add column if not exists translated_at timestamptz;

update public.news_items
set translation_status = 'skipped'
where lang = 'zh'
  and translation_status = 'not_requested';

drop index if exists news_items_search_idx;
alter table public.news_items drop column if exists search_text;
alter table public.news_items
  add column search_text tsvector generated always as (
    to_tsvector(
      'simple',
      coalesce(title, '') || ' ' ||
      coalesce(title_zh, '') || ' ' ||
      coalesce(source_name, '') || ' ' ||
      coalesce(summary, '') || ' ' ||
      coalesce(summary_zh, '') || ' ' ||
      coalesce(content_excerpt, '') || ' ' ||
      coalesce(content_text, '') || ' ' ||
      coalesce(content_text_zh, '')
    )
  ) stored;

create index if not exists news_items_search_idx
  on public.news_items using gin (search_text);

comment on column public.news_items.title_zh is
  'Simplified Chinese title translation. The source title remains in title.';
comment on column public.news_items.summary_zh is
  'Simplified Chinese summary translation. The source summary remains in summary.';
comment on column public.news_items.content_text_zh is
  'Paragraph-preserving Simplified Chinese body translation. The source body remains in content_text.';
comment on column public.news_items.translation_status is
  'Translation lifecycle: not_requested, translated, skipped, or failed.';
comment on column public.news_items.translated_at is
  'Timestamp of the latest translation or skip decision.';

notify pgrst, 'reload schema';
