import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"B2 · Messages、Roles 与上下文窗口","description":"","frontmatter":{},"headers":[],"relativePath":"agent-basics/02-messages-roles-context.md","filePath":"agent-basics/02-messages-roles-context.md","lastUpdated":1782376068000}');
const _sfc_main = { name: "agent-basics/02-messages-roles-context.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="b2-·-messages、roles-与上下文窗口" tabindex="-1">B2 · Messages、Roles 与上下文窗口 <a class="header-anchor" href="#b2-·-messages、roles-与上下文窗口" aria-label="Permalink to &quot;B2 · Messages、Roles 与上下文窗口&quot;">​</a></h1><blockquote><p>目标：理解一次模型调用不是“发一句话”，而是发送一组带角色的消息。角色、顺序、上下文长度共同决定模型看到什么。</p></blockquote><h2 id="message-array-心智模型" tabindex="-1">Message Array 心智模型 <a class="header-anchor" href="#message-array-心智模型" aria-label="Permalink to &quot;Message Array 心智模型&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> messages</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  { role: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;system&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, content: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;你是严谨的课程助教。&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  { role: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;user&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, content: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;解释 agent loop。&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  { role: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;assistant&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, content: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;...&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  { role: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;user&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, content: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;给我一个 TypeScript 例子。&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">];</span></span></code></pre></div><p>模型不会自动知道历史。你每次请求带进去什么，它就只能基于什么回答。</p><h2 id="role-的职责边界" tabindex="-1">Role 的职责边界 <a class="header-anchor" href="#role-的职责边界" aria-label="Permalink to &quot;Role 的职责边界&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Role</th><th>用途</th><th>不该放什么</th></tr></thead><tbody><tr><td>system</td><td>长期行为边界、身份、输出原则</td><td>本次临时输入、用户私密事实</td></tr><tr><td>developer</td><td>应用开发者给模型的执行约束</td><td>可被用户覆盖的偏好</td></tr><tr><td>user</td><td>本次任务、问题、业务输入</td><td>高权限系统规则</td></tr><tr><td>assistant</td><td>历史回答、工具请求、推理结果</td><td>伪造的工具结果</td></tr><tr><td>tool</td><td>工具执行后的观察结果</td><td>未执行的猜测</td></tr></tbody></table><h2 id="上下文窗口" tabindex="-1">上下文窗口 <a class="header-anchor" href="#上下文窗口" aria-label="Permalink to &quot;上下文窗口&quot;">​</a></h2><p>上下文窗口是模型本次能看到的 token 上限。它不是无限记忆，也不是越大越好。</p><table tabindex="0"><thead><tr><th>现象</th><th>原因</th><th>应对</th></tr></thead><tbody><tr><td>长对话后忘记早期约定</td><td>早期消息被截断或稀释</td><td>摘要、关键事实 pinning</td></tr><tr><td>回答变慢变贵</td><td>输入 token 变多</td><td>压缩历史、只带相关上下文</td></tr><tr><td>模型忽略中间资料</td><td>长上下文注意力分布不均</td><td>排序、分段、引用</td></tr><tr><td>用户新要求冲突</td><td>指令层级和近因影响叠加</td><td>明确优先级和冲突处理</td></tr></tbody></table><h2 id="工程拆解" tabindex="-1">工程拆解 <a class="header-anchor" href="#工程拆解" aria-label="Permalink to &quot;工程拆解&quot;">​</a></h2><p>构建 messages 时，建议分四层：</p><ol><li><strong>稳定规则</strong>：system / developer，少改、短而硬。</li><li><strong>任务输入</strong>：当前 user request，保留原文。</li><li><strong>必要历史</strong>：最近几轮对话或摘要。</li><li><strong>外部上下文</strong>：检索片段、工具结果、结构化状态。</li></ol><p>每层都要能解释“为什么这段需要进上下文”。</p><h2 id="与-agent-的关系" tabindex="-1">与 Agent 的关系 <a class="header-anchor" href="#与-agent-的关系" aria-label="Permalink to &quot;与 Agent 的关系&quot;">​</a></h2><p>Agent loop 每一步都会产生新 messages：</p><ul><li>assistant 提出工具调用。</li><li>本地代码执行工具。</li><li>tool 消息回传结果。</li><li>assistant 基于 observation 决定下一步。</li></ul><p>这就是为什么 agent 不是“一次更聪明的 prompt”，而是多轮消息状态机。</p><h2 id="自检练习" tabindex="-1">自检练习 <a class="header-anchor" href="#自检练习" aria-label="Permalink to &quot;自检练习&quot;">​</a></h2><p>把一个客服场景拆成 messages：</p><ul><li>system 里放哪些不变规则？</li><li>user 里放哪些本次问题？</li><li>tool 里放哪些订单查询结果？</li><li>哪些历史对话可以摘要，哪些必须原文保留？</li></ul><h2 id="记住一句话" tabindex="-1">记住一句话 <a class="header-anchor" href="#记住一句话" aria-label="Permalink to &quot;记住一句话&quot;">​</a></h2><p>上下文不是垃圾桶；它是模型本次推理的工作台。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("agent-basics/02-messages-roles-context.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _02MessagesRolesContext = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _02MessagesRolesContext as default
};
